import { ContentProvider } from '@/hooks/main-menu';
import { MainLayout } from '@/layouts/main';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Github Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      
        <div className={inter.className}>
          <MainLayout />
        </div>
    </>
  );
}
